/** Editor text (dev only, so English and kept out of src/i18n/nl.ts). */
export const text = {
  editor: 'Editor',
  edit: 'Edit',
  clearPuzzle: 'Clear',
  unsaved: 'unsaved',
  new: 'New',
  save: 'Save',
  saved: 'Saved',
  play: 'play ↗',
  name: 'name',
  start: 'start',
  loading: 'Loading…',
  loadFailed: 'Could not load puzzles. Is the dev server running (npm run dev)?',

  preview: 'Preview',
  solvedView: 'solved',
  openView: 'open',
  down: '↓',
  up: '↑',
  hints: 'Hints',
  answer: 'Answer',
  hint: 'Hint',
  addHint: 'Add hint',
  remove: 'Remove hint',
  reorder: 'Reorder',
  moveUp: 'Move up',
  moveDown: 'Move down',
  help: '_p previous · _a answer · Enter new hint · Alt+↑/↓ move · Backspace on empty row remove · Ctrl+S save',

  unsavedTitle: 'Unsaved changes',
  unsavedText: 'Your changes will be lost.',
  discard: 'Discard',
  cancel: 'Cancel',
  saveFailed: 'Save failed',

  unknownDollar: 'unknown $…$ code, use _p or _a',
  unknownUnderscore: 'unknown _ code, use _p or _a',
  twice: (code: string) => `${code} used more than once`,
  invalidId: 'id must be a whole number ≥ 0',
  invalidName: 'name may only contain letters, digits, - and _',
  emptyStart: 'start word is empty',
  noHints: 'add at least one hint',
  incompleteRow: (n: number) => `hint ${n}: needs both answer and hint`,
  invalidRow: (n: number, error: string) => `hint ${n}: ${error}`,
}
